function errorPage(req, res) {
    let code = 404;
    let status = "NOT_FOUND";
    let page = `<html lang=en><meta charset=utf-8><meta content="width=device-width,initial-scale=1"name=viewport><meta content=#000 name=theme-color><title>${code}: ${status}</title><style>html{font-size:62.5%;box-sizing:border-box}*,::after,::before{box-sizing:inherit}body{font-family:sf pro text,sf pro icons,helvetica neue,helvetica,arial,sans-serif;font-size:1.6rem;line-height:1.65;word-break:break-word;font-kerning:auto;font-variant:normal;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;text-rendering:optimizeLegibility;hyphens:auto;height:100vh;max-height:100vh;margin:0}code{font-family:Menlo,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New,monospace,serif;font-size:.92em}code:after,code:before{content:"\`"}.container{display:flex;justify-content:center;flex-direction:column;min-height:100vh}main{max-width:80rem;padding:4rem 6rem;margin:auto}.error-title{font-size:2rem;border-left:2px solid #ff0080;padding-left:22px;line-height:1.5;margin-bottom:24px;font-weight:500}main p{color:#333}.devinfo-container{border:1px solid #ddd;border-radius:4px;padding:2rem;display:flex;flex-direction:column;margin-bottom:32px}.error-code{margin:0;font-size:1.6rem;color:#000;margin-bottom:1.6rem}.devinfo-line{color:#333}.devinfo-line code,code,li{color:#000}.devinfo-line:not(:last-child){margin-bottom:8px}@media(max-width:500px){.devinfo-container .devinfo-line code{margin-top:.4rem}.devinfo-container .devinfo-line:not(:last-child){margin-bottom:1.6rem}.devinfo-container{margin-bottom:0}main{padding:1rem 2rem}body{font-size:1.4rem;line-height:1.55}}</style><div class=container><main><p class=devinfo-container>
    <span class=error-code><strong>${code}</strong>: ${status}</span><span class=devinfo-line>Code:<code>RESOURCE_NOT_FOUND</code></span><span class=devinfo-line>ID:<code>BIG_OOF</code></span></main></div>`;
    res.send(page);
    // res.sendFile(process.cwd() + '/lib/app/errorPage/error_page.html');
}

module.exports = { errorPage };